// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package mocks

import (
	"context"
	"github.com/segmentio/kafka-go"
	"sync"
)

// MessageReaderMock is a mock implementation of kafkaconsumer.MessageReader.
//
//	func TestSomethingThatUsesMessageReader(t *testing.T) {
//
//		// make and configure a mocked kafkaconsumer.MessageReader
//		mockedMessageReader := &MessageReaderMock{
//			CloseFunc: func() error {
//				panic("mock out the Close method")
//			},
//			CommitMessagesFunc: func(contextMoqParam context.Context, messages ...kafka.Message) error {
//				panic("mock out the CommitMessages method")
//			},
//			FetchMessageFunc: func(contextMoqParam context.Context) (kafka.Message, error) {
//				panic("mock out the FetchMessage method")
//			},
//		}
//
//		// use mockedMessageReader in code that requires kafkaconsumer.MessageReader
//		// and then make assertions.
//
//	}
type MessageReaderMock struct {
	// CloseFunc mocks the Close method.
	CloseFunc func() error

	// CommitMessagesFunc mocks the CommitMessages method.
	CommitMessagesFunc func(contextMoqParam context.Context, messages ...kafka.Message) error

	// FetchMessageFunc mocks the FetchMessage method.
	FetchMessageFunc func(contextMoqParam context.Context) (kafka.Message, error)

	// calls tracks calls to the methods.
	calls struct {
		// Close holds details about calls to the Close method.
		Close []struct {
		}
		// CommitMessages holds details about calls to the CommitMessages method.
		CommitMessages []struct {
			// ContextMoqParam is the contextMoqParam argument value.
			ContextMoqParam context.Context
			// Messages is the messages argument value.
			Messages []kafka.Message
		}
		// FetchMessage holds details about calls to the FetchMessage method.
		FetchMessage []struct {
			// ContextMoqParam is the contextMoqParam argument value.
			ContextMoqParam context.Context
		}
	}
	lockClose          sync.RWMutex
	lockCommitMessages sync.RWMutex
	lockFetchMessage   sync.RWMutex
}

// Close calls CloseFunc.
func (mock *MessageReaderMock) Close() error {
	if mock.CloseFunc == nil {
		panic("MessageReaderMock.CloseFunc: method is nil but MessageReader.Close was just called")
	}
	callInfo := struct {
	}{}
	mock.lockClose.Lock()
	mock.calls.Close = append(mock.calls.Close, callInfo)
	mock.lockClose.Unlock()
	return mock.CloseFunc()
}

// CloseCalls gets all the calls that were made to Close.
// Check the length with:
//
//	len(mockedMessageReader.CloseCalls())
func (mock *MessageReaderMock) CloseCalls() []struct {
} {
	var calls []struct {
	}
	mock.lockClose.RLock()
	calls = mock.calls.Close
	mock.lockClose.RUnlock()
	return calls
}

// CommitMessages calls CommitMessagesFunc.
func (mock *MessageReaderMock) CommitMessages(contextMoqParam context.Context, messages ...kafka.Message) error {
	if mock.CommitMessagesFunc == nil {
		panic("MessageReaderMock.CommitMessagesFunc: method is nil but MessageReader.CommitMessages was just called")
	}
	callInfo := struct {
		ContextMoqParam context.Context
		Messages        []kafka.Message
	}{
		ContextMoqParam: contextMoqParam,
		Messages:        messages,
	}
	mock.lockCommitMessages.Lock()
	mock.calls.CommitMessages = append(mock.calls.CommitMessages, callInfo)
	mock.lockCommitMessages.Unlock()
	return mock.CommitMessagesFunc(contextMoqParam, messages...)
}

// CommitMessagesCalls gets all the calls that were made to CommitMessages.
// Check the length with:
//
//	len(mockedMessageReader.CommitMessagesCalls())
func (mock *MessageReaderMock) CommitMessagesCalls() []struct {
	ContextMoqParam context.Context
	Messages        []kafka.Message
} {
	var calls []struct {
		ContextMoqParam context.Context
		Messages        []kafka.Message
	}
	mock.lockCommitMessages.RLock()
	calls = mock.calls.CommitMessages
	mock.lockCommitMessages.RUnlock()
	return calls
}

// FetchMessage calls FetchMessageFunc.
func (mock *MessageReaderMock) FetchMessage(contextMoqParam context.Context) (kafka.Message, error) {
	if mock.FetchMessageFunc == nil {
		panic("MessageReaderMock.FetchMessageFunc: method is nil but MessageReader.FetchMessage was just called")
	}
	callInfo := struct {
		ContextMoqParam context.Context
	}{
		ContextMoqParam: contextMoqParam,
	}
	mock.lockFetchMessage.Lock()
	mock.calls.FetchMessage = append(mock.calls.FetchMessage, callInfo)
	mock.lockFetchMessage.Unlock()
	return mock.FetchMessageFunc(contextMoqParam)
}

// FetchMessageCalls gets all the calls that were made to FetchMessage.
// Check the length with:
//
//	len(mockedMessageReader.FetchMessageCalls())
func (mock *MessageReaderMock) FetchMessageCalls() []struct {
	ContextMoqParam context.Context
} {
	var calls []struct {
		ContextMoqParam context.Context
	}
	mock.lockFetchMessage.RLock()
	calls = mock.calls.FetchMessage
	mock.lockFetchMessage.RUnlock()
	return calls
}
