services:

  postgres:
    image: postgres:17.6
    container_name: postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: store
      POSTGRES_USER: store
      POSTGRES_PASSWORD: storepwd
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  kafka:
    image: apache/kafka:4.1.0
    container_name: kafka
    restart: unless-stopped
    volumes:
      - kafka-data:/var/lib/kafka/data
    environment:
      KAFKA_CLUSTER_ID: 4L6g3nShT-eMCtK--X86sw
      KAFKA_NODE_ID: "1"
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,CONTROLLER://0.0.0.0:9093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,CONTROLLER:PLAINTEXT
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka:9093
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: "1"
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: "1"
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: "1"
      KAFKA_LOG_DIRS: /var/lib/kafka/data
    ports:
      - "9092:9092"

  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    container_name: kafka-ui
    restart: unless-stopped
    depends_on: [kafka]
    ports:
      - "8080:8080"
    environment:
      - KAFKA_CLUSTERS_0_NAME=local
      - KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS=kafka:9092

  storesvc:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: storesvc
    restart: unless-stopped
    depends_on:
      - postgres
      - kafka
    environment:
      PG_DSN: postgres://store:storepwd@postgres:5432/store?sslmode=disable
      KAFKA_BROKERS: kafka:9092
      KAFKA_TOPIC: store
      KAFKA_GROUP: storesvc
      HTTP_ADDR: ":8081"
      WARMUP_LIMIT: "0"
      CACHE_CAPACITY: "1000"
      AUTO_MIGRATE: "true"
    ports:
      - "8081:8081"

volumes:
  pgdata:
  kafka-data:
